AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  line-chat-bot

  Sample SAM Template for line-chat-bot

Globals:
  Function:
    Timeout: 3

Parameters:
  LineToken: 
    Type: String
    Default: t2.micro


Resources:
  WhFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: chatter/
      Handler: app.whResponder
      Runtime: python3.8
      Environment:
        Variables:
          LINE_TOKEN: !Ref LineToken
      Events:
        LineWh:
          Type: Api 
          Properties:
            Path: /line
            Method: post

  Chatter:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: chatter/
      Handler: app.whResponder
      Runtime: python3.8
      Environment:
        Variables:
          LINE_TOKEN: !Ref LineToken
      Events:
        LineWh:
          Type: Api 
          Properties:
            Path: /chatter
            Method: post
Outputs:
  MirrorInfoBot:
    Description: "api endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/line/"
  Chatter:
    Description: "api endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chatter/"
